### ISSUE TITLE
[Autonomy] Localization using AruCo Marker

### ISSUE THREAD

**Issue by SwapnilPande** [vanderbiltrobotics/NASA-RMC-2018-2019#6]
**Which section of robot code is this for?**
Vision (Markers)

**Description of feature**
Develop code to calculate the robot pose using a camera and OpenCV AruCo Camera:
* Build class for AruCo pose estimation
* Quantify the error in the pose estimation
* Determine allowed operating conditions for AruCo based pose estimation (max angle, max distance, etc.)
* Compute transformation from AruCo Coordinates to Robot Coordinates
* Build ROS Node to run calculations

**Comment by rong-wang** [comment]
AruCo marker detection code written, we are in process of testing z values returned in the camera is looking at AruCo board at an angle.

**Comment by rong-wang** [comment]
Tested AruCo detection code today with AruCo board. Results showed that at around 3 meters - 6 inches, board started being unable to be detected (board was printed on sheet of copy paper).

**Comment by partlygloudy** [comment]
Rong and I got an aruco localization node running. Still needs some improvements such as using ROS parameters to configure various settings but a very good start. After those improvements are done, we'll want to test with a variety of board configurations to see which ones produce the best results. We also need to determine how we're going to build and mount the board on the collection bin
